config/routes.rb
Rsvp::Application.routes.draw do
  resources :events do
    get :join, to: 'events#join', as: 'join'
    get :accept_request, to: 'events#accept_request', as: 'accept_request'
    get :reject_request, to: 'events#reject_request', as: 'reject_request'
  end

  devise_for :users

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

  scope :accepted, -> {where(state: 'accepted')}
  include Workflow
  workflow_column :state

  workflow do
    state :request_sent do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end

  belongs_to :event
  belongs_to :user

  def self.join_event(user_id,event_id,state)
    self.create(user_id: user_id, event_id: event_id, state: state)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :organizers, class_name: "User"
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :attendances
  has_many :users, through: :attendances

=begin
  def self.pending_request(event_id)
    Attendance.where(event_id: event_id, state: 'request_sent')
  end
=end

  def self.show_accepted_attendees(event_id)
    Attendance.accepted.where(event_id: event_id)
  end

  def slug_candidates
    [
        :title,
        [:title, :location],
    ]
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings
  has_many :events, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"
  has_many :attendances
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create,:update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :accept_request, :reject_request ]
  before_action :event_owner!, only:[:edit,:update,:destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @pending_requests = Attendance.where(event_id: Event.find_by_slug(params[:id]).id, state: 'request_sent')
    @attendees = Event.show_accepted_attendees(Event.find_by_slug(params[:id]).id)
    puts @attendees.inspect
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end

  def join
    @attendance = Attendance.join_event(current_user.id, params[:event_id],'request_sent')
    'Request Sent' if @attendance.save
    redirect_to events_path
  end

  def accept_request
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.accept!
    'Applicant Accepted' if @attendance.save
    redirect_to events_path
  end

  def reject_request
    @attendance =  Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.reject!
    'Applicant Rejected' if @attendance.save!
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by_slug(params[:id])
    end

  def event_owner!
    authenticate_user!
    if @event.organizer_id != current_user.id
      redirect_to events_path
      flash[:notice] = 'You do not have enough permissions to do this'
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id, :all_tags )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :all_tags, "List All Tags, separate each tag by a comma" %><br />
    <%= text_field_tag :all_tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Recently Created Events</h1>
<table>
  <tbody>
    <% @events.each do |event| %>
      <tr><td><span style ="font-weight:bold; font-size: 20px; margin-top: 20px;"><%= event.title %></span></td></tr>
      <tr>
        <td><span style ="font-weight:bold;">Start Date :</span><%= l event.start_date, :format => :date_format %></td>
        <td><span style ="font-weight:bold;">End Date : </span><%= l event.end_date, :format => :date_format %></td>
      </tr>
      <tr><td><span style ="font-weight:bold;">Location :</span><%= event.location %></td></tr>
      <tr><td><span style ="font-weight:bold;">Agenda :</span><%= event.agenda %></td></tr>
      <tr><td><span style ="font-weight:bold;">Address :</span><%= event.address %></td></tr>
      <tr><td><span style ="font-weight:bold;">Organized By :</span><%= User.find(event.organizer_id).email%></td></tr>
      <td><%= link_to 'Show Details', event, :class=>"btn btn-primary btn-small"%>
      <%= link_to 'Edit', edit_event_path(event), :class=>"btn btn-success btn-small" %>
      <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= l @event.start_date, :format => :date_format %>
</p>

<p>
  <strong>End date:</strong>
  <%= l @event.end_date, :format => :date_format %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= User.find(@event.organizer_id).email %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @event.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @event.updated_at %>
</p>

<p>
 <% if user_signed_in? && @event.organizer_id == current_user.id %>
  <% if @pending_requests.present? %>
    <label> Pending Requests</label><br>
    <% @pending_requests.each do |p| %>
      <%= p.user.email %>
      <%= link_to 'Accept', event_accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-success btn-small" %>
      <%= link_to 'Reject', event_reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-danger btn-small" %>
      <br>
    <% end %>
  <% end %>
</p>
<%= link_to 'Edit', edit_event_path(@event), :class=>"btn btn-success btn-small" %>
<%= link_to 'Back', events_path, :class=>"btn btn-danger btn-small" %>
<% else %>
  <%= link_to "Join", event_join_path(:event_id => @event.id), :class=>"btn btn-success btn-small" %>
<% end %><br>
  <td><%= link_to 'All Events', events_path, :class=>"btn btn-primary btn-small"%>
  <label>Attendees</label>
  <% if @attendees.present? %>
    <% @attendees.each do |attendees| %>
      <%= attendees.user.email %>
    <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsvp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %><a class="close" data-dismiss="alert">&#215;</a></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %><a class="close" data-dismiss="alert">&#215;</a></p>
<% end %>
<%= yield %>

</body>
</html>